server:
    port: 4002
spring:
    application:
        name: api-gateway
    cloud:
        config:
          uri: http://localhost:4001
        gateway:
            routes:
                - id: user-service
                  uri: lb://user-service
                  predicates:
                      - Path=/api/user/**
                - id : inventory-service
                  uri: lb://inventory-service
                  predicates:
                      - Path=/api/inventory-service/**

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
