server:
    port: 4003
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
    tomcat:
        uri-encoding: UTF-8
spring:
    application:
        name: user-service
    config:
        import: optional:configserver:http://localhost:4001
        location: es
    data:
        mongodb:
            database: dm_ecommerce_db
            host: localhost
            port: 27017
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        password: 123456
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: sys as sysdba
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    messages:
        basename: messages/messages
        encoding: UTF-8

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
