server:
  port: 4001

spring:
    application:
        name: config-server
    cloud:
      config:
          server:
              git:
                uri: https://github.com/dymmdaniel/spring-ecommerce-config
                clone-on-start: true


